### ISSUE TITLE
BIN_DIR not created by Addon installer

### ISSUE THREAD

**Issue by MFlasskamp** [LarsMichelsen/pmatic#1]
After the addon installation on my CCU all files seem to be there but python was not in the PATH. It seems that the binary directory `BIN_DIR=/usr/local/bin` was missing so the setup/init scripts failed.
I fixed that by uninstall the addon, create the folder manually and install the addon again. Not it's working properly.

**Comment by LarsMichelsen** [comment]
Thanks for reporting this issue. I just pushed a fix to the git. The new build should be ready in some minutes. The directory /usr/local/bin must have been created by another addon on my CCU before.
