### ISSUE TITLE
Suggestion: Rename 'pmatic' to 'pymatic'

### ISSUE THREAD

**Issue by jens-maus** [LarsMichelsen/pmatic#3]
Even though this sounds like a minor unimportant thing, I would like to (in this early phase of this project) propose that 'pmatic' should be renamed to be actually called 'pymatic' to better point out that this project is about "python". In addition, pymatic IMHO sounds way better and can be more easily be pronounced than "pmatic" which seems a little be odd. In addition, it is quite common that python projects like this have a prefix starting with "pyXXXXX" to immediately point out that this is about python.

I know, a minor thing. But IMHO we should at least discuss this in this early phase of the project because now renaming it shouldn't be a big hassle. So please, lets see what the general opinions are about that ;)

**Comment by MFlasskamp** [comment]
I agree with @jens-maus. "pymatic" sounds and looks far more _pythonic_. ;-)
But as it's @LarsMichelsen _baby_, the decision should be up to him.

**Comment by LarsMichelsen** [comment]
Thanks for your suggestions.

I know that there are a lot of Python projects using the py prefix, but I never really liked that. I can not tell you the exact reason, but it feels a little "uncreative". But in some cases it is totally clear to me to choose such a name, for example when implementing a protocol for a language like pySNMP or pyOpenSSL. 

The p of pmatic is also a point into the python direction, but a little more subtile.

I always pronounced pmatic like "pimätik" and I am fine with it. I don't think that it's pronouncement will be a problem.

**Comment by jens-maus** [comment]
It is of course fully up to @LarsMichelsen  to decide which name he is actually using for his project. I just wanted to raise the idea here to try to convince him that simply using a "p" might be very uncommon for python projects. It not only looks strange ("pyMatic" would look much nicer than "pMatic" IMHO), but also if he is anyway pronouncing it "pimätik" I still have the feeling that writing it "pymatic" would better match how he is pronouncing it because I pronounce pmatic like "pmätik" here.  Furthermore, I feel that if it would be called "pymatic" it would probably attract more people because they would immediately know that this is a mixture of python and homematic or a python module/application for HomeMatic applications just by reading the name.

So I am still :+1:  for renaming it.

But of course, as I said, it is up to @LarsMichelsen to decide

**Comment by LarsMichelsen** [comment]
I like to keep the name. Closing the ticket now. But thanks for your suggestions.
