### ISSUE TITLE
Snapshot release not current

### ISSUE THREAD

**Issue by jschmer** [LarsMichelsen/pmatic#9]
The snapshot release https://larsmichelsen.github.io/pmatic/pmatic-snapshot_ccu.tar.gz from https://larsmichelsen.github.io/pmatic/ is not based on the last commit as your text suggests:

> Snapshot releases are updated on each commit to the repository, but are not officially released versions. So they might not be as stable as released versions.

For example the snapshot does not include the ssl python module added with commit https://github.com/LarsMichelsen/pmatic/commit/00f03cb8d881380e043115529d8317712684ba7a 4 days ago.

**Comment by LarsMichelsen** [comment]
Danke für den Hinweis. Hab den tatsächlich kürzlich kaputt gespielt. Muss mal gucken, dass ich da ein vernünftiges Fehlerhandling einbaue.
